# Generated by Django 3.2.3 on 2021-07-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0010_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
