# Generated by Django 3.2.3 on 2021-07-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0014_auto_20210722_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateEmployee',
        ),
    ]
