# Generated by Django 3.2.3 on 2021-07-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0016_createemployee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateEmployee',
            new_name='Survey',
        ),
    ]
