# Generated by Django 3.2.3 on 2021-07-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0017_rename_createemployee_survey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
