# Generated by Django 3.2.3 on 2021-08-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0020_auto_20210801_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selections',
            name='avoid_negativity',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='avoid_overworking_yourself',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='avoid_procrastinating',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='avoid_smoking_and_nicotine',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='do_some_meditation',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='do_some_yoga',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='drink_enough_water',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='eat_enough_eggs',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='eat_more_vegetables',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='eat_some_citrus_fruits_like_oranges',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='eat_some_turkey',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='engage_your_social_support_group',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='get_support_from_colleagues',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='laugh_more',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='listen_to_soothing_music',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='practice_deep_breathing',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='pray_more',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='reduce_your_caffeine_intake',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='sleep_well',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='take_a_vacation',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='take_a_walk',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='take_green_tea_supplements',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='take_some_oatmeal',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='selections',
            name='take_some_yoghurt',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
