# Generated by Django 3.2.3 on 2021-08-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0021_auto_20210801_2044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selections',
            new_name='Selection',
        ),
    ]
