# Generated by Django 3.2.3 on 2021-08-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0024_auto_20210801_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
