# Generated by Django 3.2.3 on 2021-08-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0025_alter_method_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
