# Generated by Django 3.2.3 on 2021-07-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
