# Generated by Django 3.2.3 on 2021-08-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_check_employee_selection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
