# Generated by Django 3.2.3 on 2021-08-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_selection_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_enough_water', models.CharField(default='None', max_length=500)),
                ('take_a_walk', models.CharField(default='None', max_length=500)),
                ('laugh_more', models.CharField(default='None', max_length=500)),
                ('do_some_meditation', models.CharField(default='None', max_length=500)),
                ('get_support_from_colleagues', models.CharField(default='None', max_length=500)),
                ('avoid_smoking_and_nicotine', models.CharField(default='None', max_length=500)),
                ('avoid_procrastinating', models.CharField(default='None', max_length=500)),
                ('practice_deep_breathing', models.CharField(default='None', max_length=500)),
                ('do_some_yoga', models.CharField(default='None', max_length=500)),
                ('engage_your_social_support_group', models.CharField(default='None', max_length=500)),
                ('listen_to_soothing_music', models.CharField(default='None', max_length=500)),
                ('take_some_yoghurt', models.CharField(default='None', max_length=500)),
                ('eat_enough_eggs', models.CharField(default='None', max_length=500)),
                ('take_green_tea_supplements', models.CharField(default='None', max_length=500)),
                ('eat_some_turkey', models.CharField(default='None', max_length=500)),
                ('take_some_oatmeal', models.CharField(default='None', max_length=500)),
                ('eat_more_vegetables', models.CharField(default='None', max_length=500)),
                ('eat_some_citrus_fruits_like_oranges', models.CharField(default='None', max_length=500)),
                ('pray_more', models.CharField(default='None', max_length=500)),
                ('take_a_vacation', models.CharField(default='None', max_length=500)),
                ('sleep_well', models.CharField(default='None', max_length=500)),
                ('reduce_your_caffeine_intake', models.CharField(default='None', max_length=500)),
                ('avoid_overworking_yourself', models.CharField(default='None', max_length=500)),
                ('avoid_negativity', models.CharField(default='None', max_length=500)),
            ],
        ),
    ]
