# Generated by Django 3.2.3 on 2021-08-06 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210806_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
