# Generated by Django 3.2.3 on 2021-08-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_stresslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stresslevel',
            name='stress_level',
            field=models.CharField(max_length=10),
        ),
    ]
