# Generated by Django 3.2.3 on 2021-08-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_stresslevel_stress_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stresslevel',
            old_name='stress_level',
            new_name='fifth',
        ),
        migrations.AddField(
            model_name='stresslevel',
            name='first',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stresslevel',
            name='fourth',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stresslevel',
            name='second',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stresslevel',
            name='third',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
