# Generated by Django 3.2.3 on 2021-08-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210807_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stresslevel',
            name='fifth',
        ),
        migrations.RemoveField(
            model_name='stresslevel',
            name='first',
        ),
        migrations.RemoveField(
            model_name='stresslevel',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='stresslevel',
            name='second',
        ),
        migrations.RemoveField(
            model_name='stresslevel',
            name='third',
        ),
        migrations.AddField(
            model_name='stresslevel',
            name='levels',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10),
        ),
    ]
