# Generated by Django 3.2.3 on 2021-08-14 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210812_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stresslevel',
            name='levels',
        ),
        migrations.AddField(
            model_name='stresslevel',
            name='level',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
