# Generated by Django 3.2.3 on 2021-08-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_stresslevel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stresslevel',
            name='level',
            field=models.IntegerField(default=5),
        ),
    ]
