# Generated by Django 3.2.3 on 2021-08-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_stresslevel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='stresslevel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
